### ISSUE TITLE
Separate prep/build steps?

### ISSUE THREAD

**Issue by bayssmekanique** [bitrise-steplib/steps-ionic-archive#17]
The `1.0.0` release changed procedure for preparing and building to use two separate calls (on for each platform), rather than a single call for each of the prepare and build steps.  I'm not certain if this was purposeful, but it has caused errors with a few of my plugins and has increased the build time significantly.

Are there objections to it being a single call? (ex: `ionic "build" "--release" "--device" "ios" "android"`)

**Comment by erosdome** [comment]
We needed this change because not all versions of Ionic handles multiple platforms in one command, and they seem to be able to when using separate ones. We will revisit this question.
