### ISSUE TITLE
Using yarn as package manager

### ISSUE THREAD

**Issue by nhammond101** [bitrise-steplib/steps-ionic-archive#23]
I created an ionic app and switched out `npm` for `yarn` as the package manager.  However, the build fails on bitrise, at the archive step, if the ios or android plugin versions are set, which triggers the platforms removal and re-adding. I've attached the relevant log output below.  I'm sure it's a permissions issue, as running locally is fine.  

From a quick scan of the archive step source, it's clear that npm is being used, so I see two options, either update the docs for the step to highlight `npm` *must* be used for project module resolution.  Or make the step configurable to use yarn in addition to npm.  I'm happy to attempt to submit a PR, etc, but wondering if it's worthwhile.

> Building project
$ ionic "cordova" "platform" "rm" "ios"
✔ Creating ./www directory for you - done!
> cordova platform remove ios --save
Removing platform ios from config.xml file...
Removing ios from cordova.platforms array in package.json
Error: npm: Command failed with exit code 1 Error output:
npm ERR! path /Users/vagrant/git/node_modules/cordova-ios/node_modules/.bin/ios-sim
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/vagrant/git/node_modules/cordova-ios/node_modules/.bin/ios-sim: ../../../ios-sim/bin/ios-sim symlink target is not controlled by npm /Users/vagrant/git/node_modules/cordova-ios/node_modules/ios-sim
npm ERR! File exists: /Users/vagrant/git/node_modules/cordova-ios/node_modules/.bin/ios-sim
npm ERR! Move it away, and try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vagrant/.npm/_logs/2017-12-14T12_08_48_220Z-debug.log

**Comment by doomsayer13** [comment]
Hi @nhammond101 ,
Thank you for reporting and describing an issue, we will check it ASAP.
Feel free to create a PR. 👍

**Comment by lpusok** [comment]
From version 2.0.0 (https://github.com/bitrise-steplib/steps-ionic-archive/releases/tag/2.0.0), if yarn.lock is present in the working directly, yarn is used to install cordova and ionic packages (if related parameters are present).  `npm` is still the safest option, as ionic may use `npm` internally.
