### ISSUE TITLE
Error: archive not found at path 

### ISSUE THREAD

**Issue by EddieHoffman** [bitrise-steplib/steps-ionic-archive#35]
Hi,

I am getting the following issue when attempting to build an iOS release:

```
Non-system Ruby in use. This may cause packaging to fail.
If you use RVM, please run `rvm use system`.
If you use chruby, please run `chruby system`.
error: archive not found at path '/Users/vagrant/git/platforms/ios/matchtheteam.xcarchive'
** EXPORT FAILED **
(node:2294) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -exportArchive,-archivePath,matchtheteam.xcarchive,-exportOptionsPlist,/Users/vagrant/git/platforms/ios/exportOptions.plist,-exportPath,/Users/vagrant/git/platforms/ios/build/device
(node:2294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
no ipas generated 
```

Any idea what the issue is? Please let me know if you need any other information.

Thanks,

Eddie

**Comment by EddieHoffman** [comment]
Hi all,

Just found out this is related to https://github.com/apache/cordova-ios/issues/407

I have switched to Xcode 9.4.x stack which has resolved the issue. You should also be able to use Xcode 10 by adding the build flag '--buildFlag="-UseModernBuildSystem=0'.

Thanks.

**Comment by rthomps7** [comment]
To put this into your Bitrse step, you'll need to add the `--` at the start of the value for "Options to append to the ionic-cli build command".

So: `-- --buildFlag="-UseModernBuildSystem=0"`

**Comment by bitce** [comment]
Thanks @rthomps7 for lending a helping hand here! 🙂
