### ISSUE TITLE
Run `prepare` for the specified platform

### ISSUE THREAD

**Issue by phikes** [bitrise-steplib/steps-ionic-archive#48]
Currently this step runs `prepare` without specifying the platform eventually preparing ALL available platforms. This has been very confusing for me while using platform-specific hooks in `config.xml`.

Would it make sense to run the `prepare` command for every platform once? I had a quick look at the code and that should be easy to achieve however I am not fluent in go.

**Comment by Roland-Bak** [comment]
Hey there @phikes!

Thanks for reaching out 🙂
We are looking into the issue, could you please share some additional information your config.xml?

**Comment by phikes** [comment]
Sure, I'm gonna share it :-). In my case a script updated some generated code (see the hook), originally in the ios platform. This code would be executed when I ran this step for building my android app. This has led to some confusion.

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="de.promeldung.promeldung" ios-CFBundleIdentifier="de.promeldung.promeldung1" version="1.0.16" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
   <!-- ... -->
    <hook src="removeAdFramework.js" type="before_prepare" />
   <!-- ... -->
    <platform name="android">
  <!-- ... -->
    </platform>
    <platform name="ios">
  <!-- ... -->
    </platform>
  <!-- ... -->
</widget>
```

Thus my proposal is to only run `ionic prepare` for the platforms specified in this step. Since multiple platforms cannot be specified it needs to run these commands one after another
