### ISSUE TITLE
Support for Android app bundles

### ISSUE THREAD

**Issue by QuentinFarizon** [bitrise-steplib/steps-ionic-archive#49]
Android app bundle is an important new build system By Google, aimed at reducing build artifacts size : https://developer.android.com/platform/technology/app-bundle
It has been added to the standard "Android build" Bitrise step : https://github.com/bitrise-steplib/bitrise-step-android-build/releases/tag/0.10.0

It would be great to have an option to generate this with this Ionic archive step !

**Comment by ahvth-bitrise** [comment]
Hi @QuentinFarizon! The best place to recommend this would definitely be in our [feature request subforum](https://discuss.bitrise.io/c/feature-request). If you could take the time to post this in there and place a vote on it, that would be the best way to bring this to our developer's attention and would be much appreciated. Thanks! 😄

**Comment by QuentinFarizon** [comment]
Done : https://discuss.bitrise.io/t/support-for-android-app-bundles-for-ionic/11398

I could try to make a pull request, if someone would be able to point where changes need to be made

**Comment by QuentinFarizon** [comment]
It's still relevant and very much needed

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As I see, you have already created a post. 🙏 As this one is on our current roadmap, I close this issue and we'll share an update once we released the new version of the step.

Happy building! 🚀
