### ISSUE TITLE
Bitrise build failing - ionic-archive exited with code 127

### ISSUE THREAD

**Issue by parliament718** [bitrise-steplib/steps-ionic-archive#51]
My previously working build is suddenly failing. How can I get to the bottom of this?

<img width="798" alt="Screen Shot 2020-01-12 at 9 26 04 AM" src="https://user-images.githubusercontent.com/3580270/72220497-289f2c80-351f-11ea-8396-45994663d837.png">

I'm not sure how to do the update to 2.1 (please advise). However looking at previous passing build I see that the update was also available at the time but the step wasn't failing, which leads me to believe there problem is elsewhere. What is exit code 127?

<img width="555" alt="Screen Shot 2020-01-12 at 9 38 56 AM" src="https://user-images.githubusercontent.com/3580270/72220519-6c923180-351f-11ea-8dde-555cd523d6f2.png">

I can run `ng run app:ionic-cordova-build --platform=ios ` locally and it passes 

How can I resolve this issue?

**Comment by Roland-Bak** [comment]
Hey there @parliament718 , could you please send us a build URL so we could take a closer look? 🙂

**Comment by parliament718** [comment]
Sure here's the failing build. 
https://app.bitrise.io/build/869e4aa3ab16d865

Here's the last working build
https://app.bitrise.io/build/6d2b62da0fa6df5f

My username on Bitrise is the same as here.

Thank you for your assistance

**Comment by parliament718** [comment]
Looks like this was an angular-cli issue. 
This following fixed the issue: https://github.com/angular/angular-cli/issues/15493#issuecomment-567861956
