### ISSUE TITLE
Building both platforms (android, ios) fails while individualy works ok

### ISSUE THREAD

**Issue by pghoratiu** [bitrise-steplib/steps-ionic-archive#52]
In a workflow that has configured the build for both mobile platforms the android build completes successfully but the ios step fails. The order is android first then iOS second and the iOS build fails with a pod installation error.

If each platform is built separately everything works fine.

**Comment by Roland-Bak** [comment]
Hey @pghoratiu ! Could you please send us a build logfile of all three cases? 🙂
