### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "q"

### ISSUE THREAD

**Issue by thiagodieb** [bitrise-steplib/steps-ionic-archive#53]
While  building cordova for IOS, I had this problem with plugin: 

`

Config:
- Platform: ios
- Configuration: release
- Target: emulator
- BuildConfig: 
- Options: -- --buildFlag="-UseModernBuildSystem=0"
- Username: 
- Password: 
- RunPrepare: false
- IonicVersion: 
- CordovaVersion: 
- WorkDir: /Users/vagrant/git
- DeployDir: /Users/vagrant/deploy
- UseCache: false
Js package manager used: npm
cordova version: 9.0.0
ionic version: 5.2.3
Building project
$ ionic "cordova" "build" "--release" "--emulator" "ios" "--" "--buildFlag=-UseModernBuildSystem=0"
✔ Creating ./www directory for you - done!
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@5.1.1.

...........
        
        Adding cordova-plugin-fcm-with-dependecy-updated to package.json
        Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

        [ERROR] An error occurred while running subprocess cordova.
        cordova platform add ios --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
        
        command failed, error: exit status 1
`

**Comment by bitce** [comment]
Hi @thiagodieb! Can you please paste a build URL here, so we can take a look at the complete logs?

**Comment by thiagodieb** [comment]
Hi @bitce, sorry late reply.
Here is the build URL: https://app.bitrise.io/build/8b0f8d47f558e472#?tab=log   
This is it  ?

Thank you

**Comment by bitce** [comment]
That's it! Can you please also enable Support Access in the Settings for us, so we can take an in-depth look?

**Comment by thiagodieb** [comment]
ho,, thanks.

I'll do now

**Comment by rachid-debu** [comment]
hi, any update on this issue. I experience the same problem for another plugin

**Comment by thiagodieb** [comment]
> hi, any update on this issue. I experience the same problem for another plugin

Hi @rachid-debu i did downgrade version the cordova to 8.1.2, it is working!

**Comment by ibnunaufal** [comment]
> > hi, any update on this issue. I experience the same problem for another plugin
> 
> Hi @rachid-debu i did downgrade version the cordova to 8.1.2, it is working!

Hi, do you know how yo downgrade the version to 8.1.2 at Ionic Hub Appflow? Because the oldest cordova version at Ionic Hub is just 9.0.3,but  when i try locally in my PC its work fine with downgrading to 8.1.2. Thanks before
