### ISSUE TITLE
Failed to get cordova version, error: failed to parse version: : Malformed version

### ISSUE THREAD

**Issue by abalad** [bitrise-steplib/steps-ionic-archive#58]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _1.2.3_
- Is the issue reproducible with the latest version? _YES / NO_
- Does the issue happen sporadically, or every time? _SPORADIC / EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _YES / NO / NOT APPLICABLE_

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Error installing Cordova

$ npm "remove" "cordova" "--force"
$ npm "install" "-g" "cordova@10.0.0" "--force"
Failed to get cordova version, error: failed to parse version: : Malformed version: 
![image](https://user-images.githubusercontent.com/5459282/107824880-ed45e180-6d60-11eb-813d-9752f752b625.png)
### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 
Remote Access:	Connection successfully initiated
Agent version:	1.17.1
Hostname:	prd-atl-std-b-xcode-11-1-210212211742-HGo6e4vN7UhBk5iaY6RWhR.local
Start time:	2021-02-12T21:26:32Z
$ bitrise "run" "--config" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-agent607716738/bitrise.yml" "--inventory" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-agent607716738/bitrise.secrets.yml" "--json-params-base64" "eyJ3b3JrZmxvdyI6InByaW1hcnkifQ=="
  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝
  version: 1.45.1
INFO[21:26:34] bitrise runs in Secret Filtering mode 
INFO[21:26:34] bitrise runs in CI mode           
INFO[21:26:34] Running workflow: primary         
Switching to workflow: primary
+------------------------------------------------------------------------------+

| (0) activate-ssh-key@4.0.5                                                   |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@4.0.5                                        | 9.29 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
INFO[21:26:45] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+

| (1) git-clone@4.0                                                            |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 4.0.25                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-12T21:26:52Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- RepositoryURL: git@gitlab.com:TEMAINFO/MEDICSOLUTIONPLUS/MOBILLE.git
- CloneIntoDir: /Users/vagrant/git
- Commit: 
- Tag: 
- Branch: master
- BranchDest: 
- PRID: 0
- PRRepositoryURL: 
- PRMergeBranch: 
- ResetRepository: false
- CloneDepth: 0
- BuildURL: https://app.bitrise.io/build/bb72127db46efc05
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
$ git "init"
Initialized empty Git repository in /Users/vagrant/git/.git/
$ git "remote" "add" "origin" "git@gitlab.com:TEMAINFO/MEDICSOLUTIONPLUS/MOBILLE.git"
$ git "fetch" "origin" "refs/heads/master"
Warning: Permanently added 'gitlab.com,172.65.251.78' (ECDSA) to the list of known hosts.
From gitlab.com:TEMAINFO/MEDICSOLUTIONPLUS/MOBILLE
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
$ git "checkout" "master"
Already on 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
$ git "merge" "origin/master"
Already up to date.
$ git "submodule" "update" "--init" "--recursive"
Submodule 'src/app/shared/core' (https://bot-temainfo:[REDACTED]@gitlab.com/TEMAINFO/MEDICSOLUTIONPLUS/shared/angular/core.git) registered for path 'src/app/shared/core'
Submodule 'src/app/shared/interceptors' (https://bot-temainfo:[REDACTED]@gitlab.com/TEMAINFO/MEDICSOLUTIONPLUS/shared/angular/interceptors.git) registered for path 'src/app/shared/interceptors'
Submodule 'src/app/shared/libs/ngx-sails-io' (https://github.com/abalad/ngx-sails-io.git) registered for path 'src/app/shared/libs/ngx-sails-io'
Submodule 'src/app/shared/libs/ngxs-entity-state' (https://github.com/abalad/ngxs-entity-state.git) registered for path 'src/app/shared/libs/ngxs-entity-state'
Submodule 'src/app/shared/models' (https://bot-temainfo:[REDACTED]@gitlab.com/TEMAINFO/MEDICSOLUTIONPLUS/shared/angular/models.git) registered for path 'src/app/shared/models'
Submodule 'src/app/shared/resources' (https://bot-temainfo:[REDACTED]@gitlab.com/TEMAINFO/MEDICSOLUTIONPLUS/shared/angular/resources.git) registered for path 'src/app/shared/resources'
Submodule 'src/app/shared/services' (https://bot-temainfo:[REDACTED]@gitlab.com/TEMAINFO/MEDICSOLUTIONPLUS/shared/angular/services.git) registered for path 'src/app/shared/services'
Cloning into '/Users/vagrant/git/src/app/shared/core'...
Cloning into '/Users/vagrant/git/src/app/shared/interceptors'...
Cloning into '/Users/vagrant/git/src/app/shared/libs/ngx-sails-io'...
Cloning into '/Users/vagrant/git/src/app/shared/libs/ngxs-entity-state'...
Cloning into '/Users/vagrant/git/src/app/shared/models'...
Cloning into '/Users/vagrant/git/src/app/shared/resources'...
Cloning into '/Users/vagrant/git/src/app/shared/services'...
Submodule path 'src/app/shared/core': checked out 'ca8f07d3c60014ccff961cb66696a4d14bb75b5c'
Submodule path 'src/app/shared/interceptors': checked out 'a87fa5639c329fd367a8cb661acff070bfac768d'
Submodule path 'src/app/shared/libs/ngx-sails-io': checked out '532ad774ca235ea58f0ab5be74efcbae47e0fdd2'
Submodule path 'src/app/shared/libs/ngxs-entity-state': checked out '6876e2c76ce1a7eb14ddb2f73e3a76194eaebbc7'
Submodule path 'src/app/shared/models': checked out '91e45955d0c28196617111bba8ab2f773cd74761'
Submodule path 'src/app/shared/resources': checked out 'be2963641eee807ba479754ce4627fa0c4a51502'
Submodule path 'src/app/shared/services': checked out 'bb6bee6dc17e180f733d5e3fafebd0d1324df1ce'
Exporting git logs
$ git "log" "-1" "--format=%cn" &> out
=> GIT_CLONE_COMMIT_COMMITER_NAME
   value: Maicon Wagner
$ git "log" "-1" "--format=%ce" &> out
=> GIT_CLONE_COMMIT_COMMITER_EMAIL
   value: mister-x59@hotmail.com.br
$ git "log" "-1" "--format=%H" &> out
=> GIT_CLONE_COMMIT_HASH
   value: e7a30aef2e04820592bdd9b50dd656f5e8897e91
$ git "log" "-1" "--format=%s" &> out
=> GIT_CLONE_COMMIT_MESSAGE_SUBJECT
   value: update version to 1.3.1
$ git "log" "-1" "--format=%b" &> out
=> GIT_CLONE_COMMIT_MESSAGE_BODY
   value: 
$ git "log" "-1" "--format=%an" &> out
=> GIT_CLONE_COMMIT_AUTHOR_NAME
   value: Maicon Wagner
$ git "log" "-1" "--format=%ae" &> out
=> GIT_CLONE_COMMIT_AUTHOR_EMAIL
   value: mister-x59@hotmail.com.br
$ git "rev-list" "HEAD" "--count" &> out
=> GIT_CLONE_COMMIT_COUNT
   value: 818
Success
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@4.0                                                 | 23.22 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (2) Do anything with Script step                                             |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 2.75 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (3) certificate-and-profile-installer@1.10.3                                 |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | certificate-and-profile-installer@1.10.3                      | 7.17 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (4) npm@1.1                                                                  |
+------------------------------------------------------------------------------+
| id: npm                                                                      |
| version: 1.1.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-12T21:27:19Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- Workdir: /Users/vagrant/git
- Command: install
- NpmVersion: 
- UseCache: false
Autodetecting npm version
Checking package.json for npm version
Could not read version information from package.json
Locating system installed npm
npm found at /usr/local/bin/npm
$ npm "--version"
system npm version: 6.13.4
Running user provided command
$ npm "install"
> fsevents@1.2.9 install /Users/vagrant/git/node_modules/fsevents
> node install
node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/vagrant/git/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
> core-js@3.6.4 postinstall /Users/vagrant/git/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> core-js@2.6.11 postinstall /Users/vagrant/git/node_modules/karma/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> @angular/cli@8.3.25 postinstall /Users/vagrant/git/node_modules/@angular/cli
> node ./bin/postinstall/script.js
npm WARN The package rxjs is included as both a dev and production dependency.
added 1736 packages from 1178 contributors and audited 1740 packages in 78.216s
36 packages are looking for funding
  run `npm fund` for details
found 1140 vulnerabilities (902 low, 2 moderate, 236 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Step success
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | npm@1.1                                                       | 1.5 min  |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (5) generate-cordova-build-configuration@0.9                                 |
+------------------------------------------------------------------------------+
| id: generate-cordova-build-configuration                                     |
| version: 0.9.8                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-12T21:28:49Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[21:28:49]  * [OK] Step dependency (go) installed, available. 
ConfigsModel:
- Configuration: release
- DevelopmentTeam: 6STH26NDVJ
- CodeSignIdentity: iPhone Distribution
- AutomaticProvisioning: no
- ProvisioningProfile: a805e3ad-cf0a-4812-825c-d2690c66a83a
- PackageType: app-store
- KeystoreURL: [REDACTED]
- KeystorePassword: *****
- KeystoreAlias: [REDACTED]
- PrivateKeyPassword: *****
Adding android build config
download keystore
Adding ios build config
Generating config file
content:
{
  "android": {
    "release": {
      "keystore": "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__800509515/keystore.jks",
      "storePassword": "*****",
      "alias": "[REDACTED]",
      "password": "*****"
    }
  },
  "ios": {
    "release": {
      "codeSignIdentity": "iPhone Distribution",
      "provisioningProfile": "a805e3ad-cf0a-4812-825c-d2690c66a83a",
      "developmentTeam": "6STH26NDVJ",
      "packageType": "app-store"
    }
  }
}
The build.json path is now available in the Environment Variable: BITRISE_CORDOVA_BUILD_CONFIGURATION (value: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__800509515/build.json)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | generate-cordova-build-configuration@0.9                      | 7.54 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (6) ionic-archive@2.2                                                        |
+------------------------------------------------------------------------------+
| id: ionic-archive                                                            |
| version: 2.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-12T21:28:57Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[21:28:57]  * [OK] Step dependency (go) installed, available. 
INFO[21:28:57]  * [OK] Step dependency (gradle) installed, available. 
Config:
- Platform: ios,android
- Configuration: release
- Target: device
- BuildConfig: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__800509515/build.json
- Options: --prod --configuration=production -- --buildFlag="-UseModernBuildSystem=0"
- Username: 
- Password: 
- RunPrepare: true
- IonicVersion: 
- CordovaVersion: 10.0.0
- WorkDir: /Users/vagrant/git
- DeployDir: /Users/vagrant/deploy
- UseCache: false
Js package manager used: npm
Updating cordova version to: 10.0.0
$ npm "remove" "cordova" "--force"
$ npm "install" "-g" "cordova@10.0.0" "--force"
Failed to get cordova version, error: failed to parse version: : Malformed version: 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ionic-archive@2.2 (exit code: 1)                              | 47.93 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-ionic-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-ionic-archive               |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (7) deploy-to-bitrise-io@1                                                   |
+------------------------------------------------------------------------------+
| id: deploy-to-bitrise-io                                                     |
| version: 1.12.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-12T21:29:45Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- BuildURL: https://app.bitrise.io/build/bb72127db46efc05
- APIToken: [REDACTED]
- IsCompress: false
- ZipName: 
- DeployPath: /Users/vagrant/deploy
- NotifyUserGroups: everyone
- NotifyEmailList: 
- IsPublicPageEnabled: true
- PublicInstallPageMapFormat: {{range $index, $element := .}}{{if $index}}|{{end}}{{$element.File}}=>{{$element.URL}}{{end}}
- PermanentDownloadURLMapFormat: {{range $index, $element := .}}{{if $index}}|{{end}}{{$element.File}}=>{{$element.URL}}{{end}}
- BuildSlug: bb72127db46efc05
- TestDeployDir: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results556062036
- AppSlug: 0c8b8a9c0b0277f6
- AddonAPIBaseURL: [REDACTED]
- AddonAPIToken: [REDACTED]
- GenerateUniversalApkIfNone: true
- DebugMode: false
- BundletoolVersion: 0.13.4
Deploying the content of the Deploy directory separately
List of files to deploy
Deploying files
Success
You can find the Artifact on Bitrise, on the Build's page: https://app.bitrise.io/build/bb72127db46efc05
Upload test results
- uploading (0) test results
Success
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1                                        | 9.61 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (8) deploy-to-itunesconnect-deliver@2.17.0                                   |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| - | deploy-to-itunesconnect-deliver@2.17.0                        | 2.05 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 2.17.0 -> 2.20.2                                           |
|                                                                              |
| Release notes are available below                                            |
| ...github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/releases |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (9) google-play-deploy@3                                                     |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| - | google-play-deploy@3                                          | 3.35 sec |
+---+---------------------------------------------------------------+----------+
+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@4.0.5                                        | 9.29 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@4.0                                                 | 23.22 sec|
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 2.75 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | certificate-and-profile-installer@1.10.3                      | 7.17 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | npm@1.1                                                       | 1.5 min  |
+---+---------------------------------------------------------------+----------+
| ✓ | generate-cordova-build-configuration@0.9                      | 7.54 sec |
+---+---------------------------------------------------------------+----------+
| x | ionic-archive@2.2 (exit code: 1)                              | 47.93 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-ionic-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-ionic-archive               |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1                                        | 9.61 sec |
+---+---------------------------------------------------------------+----------+
| - | deploy-to-itunesconnect-deliver@2.17.0                        | 2.05 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 2.17.0 -> 2.20.2                                           |
|                                                                              |
| Release notes are available below                                            |
| ...github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/releases |
+---+---------------------------------------------------------------+----------+
| - | google-play-deploy@3                                          | 3.35 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 3.4 min                                                       |
+------------------------------------------------------------------------------+
Submitting anonymized usage information...
For more information visit:
https://github.com/bitrise-io/bitrise-plugins-analytics/blob/master/README.md
<details>
  <pre>
 
  </pre>
</details>

**Comment by bitce** [comment]
Thanks for the report @abalad! Can you allow us Support User access in the Settings of the app, so we can take a more in-depth look here?

**Comment by abalad** [comment]
@bitce  OK, I enabled.
![image](https://user-images.githubusercontent.com/5459282/110939200-cd7bec00-8313-11eb-9704-2b194afffff4.png)

**Comment by adborbas** [comment]
Hi @abalad,

Could you please fill the **Troubleshooting** part of the issue template with the required information? That would help us move in the right direction.

Thanks,
Adam
