### ISSUE TITLE
ARCHIVE FAILED IONIC

### ISSUE THREAD

**Issue by user-anonym** [bitrise-steplib/steps-ionic-archive#59]
Please help i can not build with ionic archive 

[d265a2910ffaf642.log](https://github.com/bitrise-steplib/steps-ionic-archive/files/6075484/d265a2910ffaf642.log)

** ARCHIVE FAILED **
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --debug --device exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
command failed, error: exit status 65
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ionic-archive@2 (exit code: 1)                                | 20.9 min |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-ionic-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-ionic-archive               |
+---+---------------------------------------------------------------+----------+

**Comment by mjones-droid** [comment]
Hi @user-anonym! The actual error is further up in the error log:

`error: No profiles for 'com.sabx.app.staging.a' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.sabx.app.staging.a'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Sabx' from project 'Sabx')
`
It looks like you don't have code signing set up properly on Bitrise. I recommend you check out our guide for this here: 
https://devcenter.bitrise.io/getting-started/getting-started-with-ionic-cordova-apps/#code-signing
