### ISSUE TITLE
Step is not using options when perform build

### ISSUE THREAD

**Issue by arnaugc** [bitrise-steplib/steps-ionic-archive#69]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I add an option in the step (--prod option) as seen in the summary.
Config:
  - Platform: ios,android
  - Configuration: release
  - Target: device
  - BuildConfig: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__707198112/build.json
  - Options: --prod
  - Username: 
  - Password: 
  - RunPrepare: false
  - IonicVersion: 4.12.0
  - CordovaVersion: 8.1.2
  - WorkDir: /Users/vagrant/git
  - DeployDir: /Users/vagrant/deploy
  - UseCache: false

When shows the log of build show the options:
`$ ionic "cordova" "build" "--release" "--device" "android" "--buildConfig" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__707198112/build.json" "--prod"
`

But when perform the real build the options not appear:
`> cordova build android --release --device --buildConfig /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__707198112/build.json
`

**Comment by Roland-Bak** [comment]
Hi @arnaugc 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by lpusok** [comment]
Hello @arnaugc,
In general, you will need to use `--` to pass Cordova CLI options, if that is what you are trying to do. In this case that could be `-- --prod`.

Ionic CLI uses -- to indicate further parameters are passed to Cordova CLI.
Cordova CLI uses -- to indicate further parameters are platform arguments.
