### ISSUE TITLE
Update IPA path after cordova-ios 7.0.0

### ISSUE THREAD

**Issue by QuentinFarizon** [bitrise-steplib/steps-ionic-archive#83]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.3.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

cordova-ios 7.0.0 has a breaking change regarding IPA generation path : 
```
Removed default CONFIGURATION_BUILD_DIR overrides

This will change the location of where the output files are generated.

build/emulator will become build/Debug-iphonesimulator
build/device will become build/Release-iphoneos
This will help ensure that debug and release files are never mixed up in the same directory and improves support for macOS maccatalyst builds.
```

This requires updating the lookup path in https://github.com/bitrise-steplib/steps-ionic-archive/blob/eacdc6e5028680b80b3231924aace006e03a2d7a/main.go#L354

### Bitrise info

- Build URL: https://app.bitrise.io/build/b85c56ba-ca8a-45f8-b5d3-6b08e63c56d9
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 
```
** ARCHIVE SUCCEEDED **
Non-system Ruby in use. This may cause packaging to fail.
If you use RVM, please run `rvm use system`.
If you use chruby, please run `chruby system`.
2023-08-21 17:01:03.557 xcodebuild[50813:93869] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/69/qgnyrbkx23dbp0p6p_b6bc9m0000gn/T/Boks preprod_2023-08-21_17-01-03.557.xcdistributionlogs".
Exported Boks preprod to: /Users/vagrant/git/platforms/ios/build/Release-iphoneos
** EXPORT SUCCEEDED **
Collecting android outputs
The aab path is now available in the Environment Variable: BITRISE_AAB_PATH (value: /Users/vagrant/deploy/app-release.aab)
The aab paths are now available in the Environment Variable: BITRISE_AAB_PATH_LIST (value: /Users/vagrant/deploy/intermediary-bundle.aab|/Users/vagrant/deploy/app-release.aab)
no ipas generated
```

**Comment by ludovictomlo** [comment]
Is this repo being maintained or should i fork it and update it?
Any idea how much time would it take for the Bitrise team to validate and merge the PR with the new step once created?

**Comment by QuentinFarizon** [comment]
Still very much an issue, why isnt there any progress on this issue ? Year old new version of Ionic is not supported

**Comment by lpusok** [comment]
Hello @QuentinFarizon 
To support this correctly has taken a bit too long indeed.
Original support for corrdova-ios@7 was released in https://github.com/bitrise-steplib/steps-ionic-archive/releases/tag/2.3.2, that release did not support cordova-ios<6. https://github.com/bitrise-steplib/steps-ionic-archive/releases/tag/2.3.3 fixes that.
